// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	configs "github.com/KejawenLab/bima/v2/configs"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GormModel is an autogenerated mock type for the GormModel type
type GormModel struct {
	mock.Mock
}

// IsSoftDelete provides a mock function with given fields:
func (_m *GormModel) IsSoftDelete() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetCreatedAt provides a mock function with given fields: _a0
func (_m *GormModel) SetCreatedAt(_a0 time.Time) {
	_m.Called(_a0)
}

// SetCreatedBy provides a mock function with given fields: user
func (_m *GormModel) SetCreatedBy(user *configs.User) {
	_m.Called(user)
}

// SetDeletedAt provides a mock function with given fields: _a0
func (_m *GormModel) SetDeletedAt(_a0 time.Time) {
	_m.Called(_a0)
}

// SetDeletedBy provides a mock function with given fields: user
func (_m *GormModel) SetDeletedBy(user *configs.User) {
	_m.Called(user)
}

// SetSyncedAt provides a mock function with given fields: _a0
func (_m *GormModel) SetSyncedAt(_a0 time.Time) {
	_m.Called(_a0)
}

// SetUpdatedAt provides a mock function with given fields: _a0
func (_m *GormModel) SetUpdatedAt(_a0 time.Time) {
	_m.Called(_a0)
}

// SetUpdatedBy provides a mock function with given fields: user
func (_m *GormModel) SetUpdatedBy(user *configs.User) {
	_m.Called(user)
}

// TableName provides a mock function with given fields:
func (_m *GormModel) TableName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewGormModel interface {
	mock.TestingT
	Cleanup(func())
}

// NewGormModel creates a new instance of GormModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGormModel(t mockConstructorTestingTNewGormModel) *GormModel {
	mock := &GormModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
