// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	configs "github.com/KejawenLab/bima/v2/configs"
	mock "github.com/stretchr/testify/mock"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: template, modulePath, packagePath, templatePath
func (_m *Generator) Generate(template *configs.Template, modulePath string, packagePath string, templatePath string) {
	_m.Called(template, modulePath, packagePath, templatePath)
}

type NewGeneratorT interface {
	mock.TestingT
	Cleanup(func())
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGenerator(t NewGeneratorT) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
