// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Module is an autogenerated mock type for the Module type
type Module struct {
	mock.Mock
}

// Consume provides a mock function with given fields:
func (_m *Module) Consume() {
	_m.Called()
}

// Populete provides a mock function with given fields:
func (_m *Module) Populete() {
	_m.Called()
}

type mockConstructorTestingTNewModule interface {
	mock.TestingT
	Cleanup(func())
}

// NewModule creates a new instance of Module. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewModule(t mockConstructorTestingTNewModule) *Module {
	mock := &Module{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
