// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MuxMiddlewares is an autogenerated mock type for the MuxMiddlewares type
type MuxMiddlewares struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MuxMiddlewares) Execute(_a0 http.Handler) http.Handler {
	ret := _m.Called(_a0)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

type NewMuxMiddlewaresT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMuxMiddlewares creates a new instance of MuxMiddlewares. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMuxMiddlewares(t NewMuxMiddlewaresT) *MuxMiddlewares {
	mock := &MuxMiddlewares{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
